name: ABBLESS APK Builder

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ABBLESS
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.10.2

      - name: Make Gradle Wrapper executable
        run: chmod +x gradlew

      - name: Build ABBLESS
        run: ./gradlew assembleDebug

      - name: Upload ABBLESS APK
        uses: actions/upload-artifact@v4
        with:
          name: ABBLESS-debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

